ZPtest_demo/myapp/urls.py
from django.urls import path

from myapp.views import *

app_name = 'NB'

urlpatterns = [
    path('user_home/', user_home, name='user_home'),
    path('company_home/', company_home, name='company_home'),
    path('user_register_home/', user_register_home, name='user_register_home'),
    path('company_register_home/', company_register_home, name='company_register_home'),
    path('user_register/', user_register, name='user_register'),
    path('company_register/', company_register, name='company_register'),
    path('user_login/', user_login, name='user_login'),
    path('company_login/', company_login, name='company_login'),
    path('go_user_reset/', go_user_reset, name='go_user_reset'),
    path('go_company_reset/', go_company_reset, name='go_company_reset'),
    path('go_company_mine/', go_company_mine, name='go_company_mine'),
    path('go_user_mine/', go_user_mine, name='go_user_mine'),
    path('go_user_vip/', go_user_vip, name='go_user_vip'),
    path('go_user_vip/', go_company_vip, name='go_company_vip'),
    path('go_company_zhiweisousuo/', go_company_zhiweisousuo, name='go_company_zhiweisousuo'),
    path('go_company_shoujianxiang/', go_cpmpany_shoujianxiang, name='go_cpmpany_shoujianxiang'),
    path('go_company_rencaijia/', go_company_recaija, name='go_company_recaija'),
    path('upload_job_home/', upload_job_home, name='upload_job_home'),
    path('save_job/', save_job, name='save_job'),
    path('save_xinxi/', save_xinxi, name='save_xinxi'),
    path('user_set/', email_phone_set, name='user_set'),
    path('user_reset/', email_phone_reset, name='user_reset'),
    path('upload_resume_home/', upload_resume_home, name='upload_resume_home'),
    path('zwss_home/', zwss_home, name='zwss_home'),
    path('company_set/', email_phone_set, name='company_set'),
    path('company_reset/', email_phone_reset, name='company_reset'),
    path('set_phone/', set_phone, name='set_phone'),
    path('set_email/', set_email, name='set_email')
]

ZPtest_demo/templates/company_vip.html
<!DOCTYPE html>
{% load static %}
<html lang="zxx" class="no-js">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="img/fav.png">
    <meta name="author" content="codepixer">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta charset="UTF-8">
    <title>会员中心</title>

    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'company/linearicons.css' %}">
    <link rel="stylesheet" href="{% static 'company/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'company/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'company/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'company/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'company/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'company/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'company/main.css' %}">
    <link rel="stylesheet" href="{% static 'list_yemian/reset.css' %}">
    <link rel="stylesheet" href="{% static 'list_yemian/public.css' %}">
    <link rel="stylesheet" href="{% static 'list_yemian/recruitmenting.css' %}">
</head>
<body>

<header id="header" id="home">
    <div class="container">
        <div class="row align-items-center justify-content-between d-flex">
            <div id="logo">
                <a style="font-size: 30px">博纳人才网</a>
            </div>
            <nav id="nav-menu-container">
                <ul class="nav-menu">
                    <li class="menu-active"><a href="{% url "NB:go_company_mine" %}">我的主页</a></li>
                    <li class="menu-has-children"><a href="">职位管理</a>
                        <ul>
                            <li><a href="">职位发布</a></li>
                            <li><a href="">查看发布岗位</a></li>
                        </ul>
                    </li>
                    <li><a href="">邀约纪录</a></li>
                    <li><a href="">职位搜索</a></li>
                    <li><a href="{% url 'NB:go_cpmpany_shoujianxiang' %}">收件箱</a></li>
                    <li><a href="{% url 'NB:go_company_recaija' %}">公司人才夹</a></li>
                    <li class="menu-has-children"><a href="">个人中心</a>
                        <ul>
                            <li><a href="">修改公司基本信息</a></li>
                            <li><a href="{% url 'NB:go_user_reset' %}">修改密码</a></li>
                            <li><a href="">会员信息</a></li>
                        </ul>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
</header>

<section class="banner-area relative" id="home">

    <div class="overlay overlay-bg" style="height: 723px">
        <div style="margin-left: 15%;margin-top: 7%;width:600px;height: 400px">
            <div style="width: 800px;height: 400px;">
                <div style="height: 15%"></div>
                <div style="background-color:white;width: 900px;height: 558px;">
                    <div>
                        <div style="height: 20px">
                        </div>
                        <div style="font-size: 25px;width: 12%;height:10%;"><b style="color: black">会员内容</b>
                        </div>
                        <hr>
                        <hr>
                        <div style="margin-top: 8%;margin-left: 10%;width: 90%;height:300px">
                            <div style="width:30%;float: left;text-align: center;vertical-align: center;height: 100%;border: 1px solid black">
                                <div style="height: 10%"></div>
                                <p><h1 style="color: #005cbf;">套餐A：￥2500.00
                                    </h1>
                                </p>
                                <div style="height: 20%;"></div>
                                <p style="font-size: 20px;height: 15%"><b style="color:red;">20</b>个岗位发布</p>
                                <p style="font-size: 20px;height: 15%"><b style="color:red;">1500</b>份简历下载</p>
                                <p style="font-size: 20px;height: 15%"><b style="color:red;">500</b>封邮件邀请</p>
                                <div style="height: 8%"></div>
                                <input type="checkbox" style="text-align: right;width: 20px;height: 20px">
                            </div>
                            <div style="width:30%;float: left;text-align: center;vertical-align: center;height: 100%;border: 1px solid black">
                                <div style="height: 10%"></div>
                                <p><h1 style="color: #005cbf;">套餐B：￥4500.00
                                    </h1>
                                </p>
                                <div style="height: 20%;"></div>
                                <p style="font-size: 20px;height: 15%"><b style="color:red;">40</b>个岗位发布</p>
                                <p style="font-size: 20px;height: 15%"><b style="color:red;">3000</b>份简历下载</p>
                                <p style="font-size: 20px;height: 15%"><b style="color:red;">1000</b>封邮件邀请</p>
                                <div style="height: 8%"></div>
                                <input type="checkbox" style="text-align: right;width: 20px;height: 20px">
                            </div>
                            <div style="width:30%;float: left;text-align: center;vertical-align: center;height: 100%;border: 1px solid black">
                                <div style="height: 10%"></div>
                                <p><h1 style="color: #005cbf;">套餐C：￥7500.00
                                    </h1>
                                </p>
                                <div style="height: 20%;"></div>
                                <p style="font-size: 20px;height: 15%"><b style="color:red;">80</b>个岗位发布</p>
                                <p style="font-size: 20px;height: 15%"><b style="color:red;">3000</b>份简历下载</p>
                                <p style="font-size: 20px;height: 15%"><b style="color:red;">1000</b>封邮件邀请</p>
                                <div style="height: 8%"></div>
                                <input type="checkbox" style="text-align: right;width: 20px;height: 20px">
                            </div>

                        </div>
                        <div style="margin-top: 10%;margin-left: 40%">
                            <button href=""><b style="color: red">点击购买</b></button>
                            <button href="" style="margin-left: 10%"><b style="color: black">取消</b></button>
                        </div>
                    </div>

                </div>

            </div>
        </div>
    </div>
    <div class="row fullscreen d-flex align-items-center justify-content-center">
    </div>
</section>
<footer class="footer-area section-gap" style="height: 250px">
    <div class="container" style="height: 100px">
        <div class="row" style="margin-left: 300px">
            <p>
                <a href="#">关 于 我 们</a>---<a href="#">广 告 合 作 </a>---<a href="#">联 系 我 们 </a>---<a href="#">免 责 声 明 </a>---<a
                    href="#">在 线 投 稿 </a>---<a href="#">投 诉 建 议 </a>
            </p>
        </div>

        <div class="row footer-bottom d-flex justify-content-between" style="margin-left: 305px">

            Copyright &copy;<script>document.write(new Date().getFullYear());</script>
            python1805 NB 0.1 QUAN ZHAN SAN REN PRODUCT. 版权所有
        </div>
    </div>
</footer>
<!-- End footer Area -->

<script src="{% static 'company/jquery-2.2.4.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="{% static 'company/bootstrap.min.js' %}"></script>

<script src="{% static 'company/easing.min.js' %}"></script>
<script src="{% static 'company/hoverIntent.js' %}"></script>
<script src="{% static 'company/superfish.min.js' %}"></script>
<script src="{% static 'company/jquery.ajaxchimp.min.js' %}"></script>
<script src="{% static 'company/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'company/owl.carousel.min.js' %}"></script>
<script src="{% static 'company/jquery.sticky.js' %}"></script>
<script src="{% static 'company/jquery.nice-select.min.js' %}"></script>
<script src="{% static 'company/parallax.min.js' %}"></script>
<script src="{% static 'company/mail-script.js' %}"></script>
<script src="{% static 'company/main.js' %}"></script>
</body>
</html>




ZPtest_demo/templates/company_zhiweilist.html
<!DOCTYPE html>
{% load static %}
<html lang="zxx" class="no-js">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="img/fav.png">
    <meta name="author" content="codepixer">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta charset="UTF-8">
    <title>欢迎登录博纳人才网</title>

    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'company/linearicons.css' %}">
    <link rel="stylesheet" href="{% static 'company/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'company/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'company/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'company/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'company/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'company/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'company/main.css' %}">
    <link rel="stylesheet" href="{% static 'list_yemian/reset.css' %}">
    <link rel="stylesheet" href="{% static 'list_yemian/public.css' %}">
    <link rel="stylesheet" href="{% static 'list_yemian/recruitmenting.css' %}">
</head>
<body>

<header id="header" id="home">
    <div class="container">
        <div class="row align-items-center justify-content-between d-flex">
            <div id="logo">
                <a style="font-size: 30px">博纳人才网</a>
            </div>
            <nav id="nav-menu-container">
                <ul class="nav-menu">
                    <li class="menu-active"><a href="{% url "NB:go_company_mine" %}">我的主页</a></li>
                    <li class="menu-has-children"><a href="">职位管理</a>
                        <ul>
                            <li><a href="">职位发布</a></li>
                            <li><a href="{% url 'NB:go_company_zhiweisousuo' %}">查看发布岗位</a></li>
                        </ul>
                    </li>
                    <li><a href="">邀约纪录</a></li>
                    <li><a href="">职位搜索</a></li>
                    <li><a href="{% url 'NB:go_cpmpany_shoujianxiang' %}">收件箱</a></li>
                    <li><a href="">公司人才夹</a></li>
                    <li class="menu-has-children"><a href="">个人中心</a>
                        <ul>
                            <li><a href="">修改公司基本信息</a></li>
                            <li><a href="{% url 'NB:go_user_reset' %}">修改密码</a></li>
                            <li><a href="">会员信息</a></li>
                        </ul>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
</header>

<section class="banner-area relative" id="home">

    <div class="overlay overlay-bg" style="height: 723px">
        <div style="margin-left: 350px;margin-top: 100px;width:600px;height: 400px">
            <div style="float: left;width: 210px;height: 50px;">
                <p style="font-size: 70px;color: blue;margin-top: 16px"></p>
            </div>
            <div style="float: left;width: 240px;height: 10px">

            </div>
            <div style="width: 800px;height: 400px;">
                <div style="height: 65px"></div>
                <div style="background-color:gray;width: 900px;height: 558px">
                    <div style="width: 900px;height: 350px">
                        <div class="plate-bottom" style="width: 900px;line-height: 45px;">
                            <div class="thead" style="width: 900px;line-height: 45px;">
                                <span class="thead-one" style="width: 30%;font-size: 30px"><b style="color: white">职位信息</b></span>
                                <span class="thead-two" style="width: 58%"></span>
                                <span class="thead-three" style="width: 10%;font-size: 30px"><b style="color: white">操作</b></span>
                            </div>
                            <div class="position-list">
                                <div class="position" style="height: 135px">
                                    <div class="select fl">
                                        <input type="checkbox">
                                    </div>
                                    <div class="name fl" style="width: 53%;height: 25px">
                                        <p><span><b style="color: #005cbf">PHP高级工程师</b> </span></p>
                                        <ul style="color: black">
                                            <li>武汉</li>
                                            <li>|</li>
                                            <li>1-3年工作经验</li>
                                            <li>|</li>
                                            <li>本科学历</li>
                                            <li>|</li>
                                            <li>4k-5k</li>
                                        </ul>
                                    </div>
                                    <div class="edit fr" style="width: 12%;color: crimson">
                                        <a class="open" href="" style="color: crimson">下线</a>&nbsp;&nbsp;
                                        <a href="" style="color: crimson">修改</a>
                                    </div>
                                </div>
                                <div class="position" style="height: 135px">
                                    <div class="select fl">
                                        <input type="checkbox">
                                    </div>
                                    <div class="name fl" style="width: 53%">
                                        <p><span><b style="color: #005cbf">PHP高级工程师</b> </span></p>
                                        <ul style="color: black">
                                            <li>武汉</li>
                                            <li>|</li>
                                            <li>1-3年工作经验</li>
                                            <li>|</li>
                                            <li>本科学历</li>
                                            <li>|</li>
                                            <li>4k-5k</li>
                                        </ul>
                                    </div>
                                    <div class="edit fr" style="width: 12%;">
                                        <a class="open" href="" style="color: crimson">下线</a>&nbsp;&nbsp;
                                        <a href="" style="color: crimson">修改</a>
                                    </div>
                                </div>
                                <div class="position" style="height: 135px">
                                    <div class="select fl">
                                        <input type="checkbox">
                                    </div>
                                    <div class="name fl" style="width: 53%">
                                        <p><span><b style="color: #005cbf">PHP高级工程师</b> </span></p>
                                        <ul style="color: black">
                                            <li>武汉</li>
                                            <li>|</li>
                                            <li>1-3年工作经验</li>
                                            <li>|</li>
                                            <li>本科学历</li>
                                            <li>|</li>
                                            <li>4k-5k</li>
                                        </ul>
                                    </div>
                                    <div class="edit fr" style="width: 12%;">
                                        <a class="open" href="" style="color: crimson">下线</a>&nbsp;&nbsp;
                                        <a href="" style="color: crimson">修改</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="plate-bottom" style="width: 900px;height: 30px;background-color: gray">
                            <div class="thead"
                                 style="width: 900px;height: 30px;background-color: gray;line-height: 70px;font-size: 15px">
                                <span style="width: 5%"></span>
                                <a href=""><span style="width: 10%">首页</span></a>
                                <a href=""><span style="width: 3%">1</span></a>
                                <a href=""><span style="width: 3%">2</span></a>
                                <a href=""><span style="width: 3%">3</span></a>
                                <a href=""><span style="width: 5%">.......</span></a>
                                <a href=""><span style="width: 5%">下一页</span></a>
                            </div>
                        </div>

                    </div>
                </div>

            </div>
        </div>
    </div>
    <div class="row fullscreen d-flex align-items-center justify-content-center">
    </div>
</section>
<footer class="footer-area section-gap" style="height: 250px">
    <div class="container" style="height: 100px">
        <div class="row" style="margin-left: 300px">
            <p>
                <a href="#">关 于 我 们</a>---<a href="#">广 告 合 作 </a>---<a href="#">联 系 我 们 </a>---<a href="#">免 责 声 明 </a>---<a
                    href="#">在 线 投 稿 </a>---<a href="#">投 诉 建 议 </a>
            </p>
        </div>

        <div class="row footer-bottom d-flex justify-content-between" style="margin-left: 305px">

            Copyright &copy;<script>document.write(new Date().getFullYear());</script>
            python1805 NB 0.1 QUAN ZHAN SAN REN PRODUCT. 版权所有
        </div>
    </div>
</footer>
<!-- End footer Area -->

<script src="{% static 'company/jquery-2.2.4.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="{% static 'company/bootstrap.min.js' %}"></script>

<script src="{% static 'company/easing.min.js' %}"></script>
<script src="{% static 'company/hoverIntent.js' %}"></script>
<script src="{% static 'company/superfish.min.js' %}"></script>
<script src="{% static 'company/jquery.ajaxchimp.min.js' %}"></script>
<script src="{% static 'company/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'company/owl.carousel.min.js' %}"></script>
<script src="{% static 'company/jquery.sticky.js' %}"></script>
<script src="{% static 'company/jquery.nice-select.min.js' %}"></script>
<script src="{% static 'company/parallax.min.js' %}"></script>
<script src="{% static 'company/mail-script.js' %}"></script>
<script src="{% static 'company/main.js' %}"></script>
</body>
</html>




ZPtest_demo/templates/user_login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>欢迎访问博纳人才网</title>
    <style type="text/css">
    body{
        background: url(../static/img/bg.jpg) no-repeat;
        background-size: cover;
    }
    *{
        margin:0;
        padding: 0;
    }
    .title{
        font-size: 80px;
        line-height: 200px;
    }
    .titlediv{
        width:1000px;
        height: 200px;
        margin:0 auto;
    }
    img{
        width: 200px;
        height: 200px;
        float:left;
    }
    .zhuce{
        width:300px;
        height: 200px;
        margin:90px auto 0;
     }
     .login{
        border:1px solid gray;
        text-align: center;
        width: 300px;
        height: 35px;
     }
   /* .login a{
        display: inline-block;
        font-size: 26px;
    }*/
    .company{

        width: 150px;
        float: left;
    }
    .user{
        background: skyblue;
        display: inline-block;
        width: 150px;
    }
    .company a {
        line-height: 35px;
        display: inline-block;
        height: 35px;
    }
    .user a{
        line-height: 35px;
        display: inline-block;
        height: 35px;
    }
    .btn{
        width: 300px;
        height: 35px;
        border-radius: 5px;
        font-size: 16px;
        margin-top: 20px;
    }
    form{
        position: relative;
    }
    .username{
        margin:15px auto 2px;
    }
    input{
        width: 300px;
        height: 28px;
        border: 1px solid gray;
    }
    .reg{
        margin-top: 17px;
        text-align: center;
    }
    .reg a:nth-child(1){
        margin-right: 30px;
    }
    .reg a{
        text-decoration: none;
        color: black;
        font-size: 18px;
    }
    .reg a:hover{
        color:blue;
    }
    .reg a:action{
        color:gray;
    }
    </style>
</head>
<body>
<div class="titlediv">
<img src="https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1547879279633&di=2be207cc066923f3105357742052e656&imgtype=0&src=http%3A%2F%2Fimage8.huangye88.cn%2F2016%2F08%2F16%2Fe71aa11fd9f72cedd7abfeed500a977d_350_350.jpg">
<h1 class="title">欢迎光临博纳人才网</h1>
</div>
<div class="zhuce">
    <div class="login">
        <div class="company"><a style="text-decoration: none" href={% url 'NB:company_home' %}>企业登录</a></div>
        <div class="user"><a style="text-decoration: none">用户登录</a></div>
    </div>

<div>

    <form method="post" action="{% url 'NB:user_login' %}">
        <div class="username"><input type="text" name="user_name"  placeholder="请输入手机号/邮箱/用户名"></div>
        <div class="password"><input type="password" name="user_pwd" placeholder="请输入密码"></div>
        <input type="submit" value="登录" class="btn"><br>
    </form>

</div>
<div class="reg">
    <a href="{% url 'NB:go_user_reset' %}">忘记密码</a>
    <a href={% url 'NB:user_register_home' %}>注册账号</a>
</div>
</div>
</body>
</html>

ZPtest_demo/templates/user_vip.html
<!DOCTYPE html>
{% load static %}
<html lang="zxx" class="no-js">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="img/fav.png">
    <meta name="author" content="codepixer">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta charset="UTF-8">
    <title>会员中心</title>

    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'company/linearicons.css' %}">
    <link rel="stylesheet" href="{% static 'company/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'company/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'company/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'company/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'company/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'company/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'company/main.css' %}">
    <link rel="stylesheet" href="{% static 'list_yemian/reset.css' %}">
    <link rel="stylesheet" href="{% static 'list_yemian/public.css' %}">
    <link rel="stylesheet" href="{% static 'list_yemian/recruitmenting.css' %}">
</head>
<body>

<header id="header" id="home">
    <div class="container">
        <div class="row align-items-center justify-content-between d-flex">
            <div id="logo">
                <a style="font-size: 30px">博纳人才网</a>
            </div>
            <nav id="nav-menu-container">
                <ul class="nav-menu">
                    <li class="menu-active"><a href="{% url "NB:go_company_mine" %}">我的主页</a></li>
                    <li class="menu-has-children"><a href="">简历管理</a>
                        <ul>
                            <li><a href="">简历浏览</a></li>
                            <li><a href="{% url 'NB:upload_resume_home' %}">上传简历</a></li>
                            <li><a href="">简历刷新</a></li>
                        </ul>
                    </li>
                    <li><a href="">邀约纪录</a></li>
                    <li><a href="">职位搜索</a></li>
                    <li><a href="">收件箱</a></li>
                    <li><a href="">公司人才夹</a></li>
                    <li class="menu-has-children"><a href="">个人中心</a>
                        <ul>
                            <li><a href="">修改公司基本信息</a></li>
                            <li><a href="{% url 'NB:go_user_reset' %}">修改密码</a></li>
                            <li><a href="">会员信息</a></li>
                        </ul>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
</header>

<section class="banner-area relative" id="home">

    <div class="overlay overlay-bg" style="height: 723px">
        <div style="margin-left: 15%;margin-top: 7%;width:600px;height: 400px">
            <div style="width: 800px;height: 400px;">
                <div style="height: 15%"></div>
                <div style="background-color:white;width: 900px;height: 558px">
                    <div>
                        <div style="height: 20px"></div>
                        <div style="font-size: 25px;width: 12%;height:10%;"><b style="color: black">会员内容</b></div>

                        <hr>
                        <hr>
                        <table border="1"
                               style="margin-top: 5%;margin-left: 15%;width: 70%;height:300px;text-align: center;vertical-align: center">
                            <tr style="height: 20%">
                                <th>非会员</th>
                                <th>会员</th>
                            </tr>
                            <tr style="height: 40%">
                                <td valign="middle">只能看到一条企业查看纪录</td>
                                <td>可查看3天内的企业查看纪录</td>
                            </tr>
                            <tr style="height: 40%">
                                <td valign="middle">不能查看在求职者的竞争力</td>
                                <td>可以查看在求职者的竞争力</td>
                            </tr>
                        </table>
                        <div style="margin-top: 10%;margin-left: 35%">
                            <button href=""><b style="color: red">点击购买</b>￥69.0</button>
                            <button href="" style="margin-left: 10%"><b style="color: black">取消</b></button>
                        </div>
                    </div>

                </div>

            </div>
        </div>
    </div>
    <div class="row fullscreen d-flex align-items-center justify-content-center">
    </div>
</section>
<footer class="footer-area section-gap" style="height: 250px">
    <div class="container" style="height: 100px">
        <div class="row" style="margin-left: 300px">
            <p>
                <a href="#">关 于 我 们</a>---<a href="#">广 告 合 作 </a>---<a href="#">联 系 我 们 </a>---<a href="#">免 责 声 明 </a>---<a
                    href="#">在 线 投 稿 </a>---<a href="#">投 诉 建 议 </a>
            </p>
        </div>

        <div class="row footer-bottom d-flex justify-content-between" style="margin-left: 305px">

            Copyright &copy;<script>document.write(new Date().getFullYear());</script>
            python1805 NB 0.1 QUAN ZHAN SAN REN PRODUCT. 版权所有
        </div>
    </div>
</footer>
<!-- End footer Area -->

<script src="{% static 'company/jquery-2.2.4.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="{% static 'company/bootstrap.min.js' %}"></script>

<script src="{% static 'company/easing.min.js' %}"></script>
<script src="{% static 'company/hoverIntent.js' %}"></script>
<script src="{% static 'company/superfish.min.js' %}"></script>
<script src="{% static 'company/jquery.ajaxchimp.min.js' %}"></script>
<script src="{% static 'company/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'company/owl.carousel.min.js' %}"></script>
<script src="{% static 'company/jquery.sticky.js' %}"></script>
<script src="{% static 'company/jquery.nice-select.min.js' %}"></script>
<script src="{% static 'company/parallax.min.js' %}"></script>
<script src="{% static 'company/mail-script.js' %}"></script>
<script src="{% static 'company/main.js' %}"></script>
</body>
</html>


