ZPtest_v01/ZPtest/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls', namespace='NB'))
]

ZPtest_v01/myapp/urls.py
from django.urls import path

from myapp.views import *

app_name = 'NB'

urlpatterns = [
    path('company_home/', company_home, name='company_home'),
    path('company_register_home/', company_register_home, name='company_register_home'),
    path('company_register/', company_register, name='company_register'),
    path('company_login/', company_login, name='company_login'),
    path('go_company_reset/', go_company_reset, name='go_company_reset'),
    path('go_company_mine/', go_company_mine, name='go_company_mine'),
    path('go_company_vip/', go_company_vip, name='go_company_vip'),
    path('go_company_zhiweisousuo/<pagenum>/', go_company_zhiweisousuo, name='go_company_zhiweisousuo'),
    path('go_company_shoujianxiang/<pagenum>/', go_cpmpany_shoujianxiang, name='go_cpmpany_shoujianxiang'),
    path('go_company_rencaijia/<pagenum>/', go_company_recaija, name='go_company_recaijia'),
    path('company_set/', email_phone_set, name='company_set'),
    path('company_reset/', email_phone_reset, name='company_reset'),
    path('set_phone/', set_phone, name='set_phone'),
    path('set_email/', set_email, name='set_email'),
    path('change_company/',change_company,name='change_company'),
    path('check_resume/<id>/',check_resume,name='check_resume'),
    path('download_resume/',download_resume,name='download_resume'),
    path('jiaru_resume/',jiaru_resume,name='jiaru_resume'),
    path('job_save/', job_release, name='job_save'),
    path('goumai_vip/',goumai_vip,name='goumai_vip'),
    path('xia_xian/<id>/',xia_xian,name='xia_xian'),
    path('re_resume/<id>/',re_resume,name='re_resume'),
    path('upload_job_home/',upload_job_home,name='upload_job_home'),
    path('company_user_name/', company_user_name, name='company_user_name'),
    path('company_name/', company_name, name='company_name'),
    path('search_company_job/<pagenum>/', search_company_job, name='search_company_job'),

    path('user_home/', user_home, name='user_home'),
    path('user_register_home/', user_register_home, name='user_register_home'),
    path('user_register/', user_register, name='user_register'),
    path('user_login/', user_login, name='user_login'),
    path('go_user_reset/', go_user_reset, name='go_user_reset'),
    path('go_user_mine/', go_user_mine, name='go_user_mine'),
    path('zwss_home/<pagenum>/', zwss_home, name='zwss_home'),
    path('user_set/', email_phone_set, name='user_set'),
    path('user_reset/', email_phone_reset, name='user_reset'),
    path('go_user_vip/', go_user_vip, name='go_user_vip'),
    path('user_zwsc/<pagenum>/', go_user_zwsc, name='user_zwsc'),
    path('user_tdjd/<pagenum>/', go_user_tdjd, name='user_tdjd'),
    path('user_pbgs/<pagenum>/', go_user_pbgs, name='user_pbgs'),
    path('user_skgw/<pagenum>/', go_user_skgw, name='user_skgw'),
    path('resume_show/', go_user_jlll, name='resume_show'),
    path('resume_upload/', go_resume_upload, name='resume_upload'),
    path('img/', img, name='img'),
    path('save_xinxi/', save_xinxi, name='save_xinxi'),
    path('change_xinxi/', change_xinxi, name='change_xinxi'),
    path('find_resume/', find_resume, name='find_resume'),
    path('resume_refresh/', resume_refresh, name='resume_refresh'),
    path('cancel_pingbi/<name>/', cancel_pingbi, name='cancel_pingbi'),
    path('zhiweishoucang_toudi/', zhiweishoucang_toudi, name='zhiweishoucang_toudi'),
    path('zhiweishoucang_shanchu/<id>/', zhiweishoucang_shanchu, name='zhiweishoucang_shanchu'),
    path('zhiwei_show/<id>/', zhiwei_show, name='zhiwei_show'),
    path('pingbi_company/', pingbi_company, name='pingbi_company'),
    path('company_show/<id>/', company_show, name='company_show'),
    path('collect_zhiwei/', collect_zhiwei, name='collect_zhiwei'),

    path('quit_login/', quit_login, name='quit_login'),
]

ZPtest_v01/templates/user/user_pingbigongsi.html
<!DOCTYPE html>
{% load static %}
<html lang="zxx" class="no-js">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="">
    <meta name="author" content="codepixer">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta charset="UTF-8">
    <title>欢迎登录博纳人才网</title>

    <link href="{% static 'user/mine/css.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'user/mine/linearicons.css' %}">
    <link rel="stylesheet" href="{% static 'user/mine/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'user/mine/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'user/mine/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'user/mine/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'user/mine/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'user/mine/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'user/mine/main.css' %}">
    <link rel="stylesheet" href="{% static 'user/mine/reset.css' %}">
    <link rel="stylesheet" href="{% static 'user/mine/public.css' %}">
    <link rel="stylesheet" href="{% static 'user/mine/recruitmenting.css' %}">
</head>
<body>

<header id="header" id="home">
    <div class="container">
        <div class="row align-items-center justify-content-between d-flex">
            <div id="logo">
                <a style="font-size: 30px">博纳人才网</a>
            </div>
            <nav id="nav-menu-container">
                <ul class="nav-menu">
                    <li class="menu-active"><a href="{% url "NB:go_user_mine" %}">我的主页</a></li>
                    <li class="menu-has-children"><a href="#">简历管理</a>
                        <ul>
                            <li><a href="{% url 'NB:find_resume' %}">简历浏览</a></li>
                            <li><a href="{% url 'NB:find_resume' %}">上传简历</a></li>
                            <li><a class="resume_refresh" href="#">简历刷新</a></li>
                        </ul>
                    </li>
                    <li><a href="{% url 'NB:user_tdjd' 1 %}">投递进度</a></li>
{#                    <li><a href="{% url 'NB:zwss_home' 1 %}">职位搜索</a></li>#}
                    <li><a href="{% url 'NB:user_pbgs' 1 %}">屏蔽公司</a></li>
                    <li><a href="{% url 'NB:user_zwsc' 1 %}">职位收藏</a></li>
                    <li><a href="{% url 'NB:user_skgw' 1 %}">谁看过我</a></li>
                    <li class="menu-has-children"><a href="#">个人中心</a>
                        <ul>
                            <li><a href="{% url 'NB:go_user_reset' %}">找回密码</a></li>
                            <li><a href="{% url 'NB:go_user_vip' %}">会员信息</a></li>
                            <li><a href="{% url 'NB:quit_login' %}">用户注销</a></li>
                        </ul>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
</header>

<section class="banner-area relative" id="home">

    <div class="overlay overlay-bg" style="height: 723px">
        <div style="margin-left: 350px;margin-top: 100px;width:600px;height: 400px">
            <div style="float: left;width: 210px;height: 50px;">
                <p style="font-size: 70px;color: blue;margin-top: 16px"></p>
            </div>
            <div style="float: left;width: 240px;height: 10px">

            </div>
            <div style="width: 800px;height: 400px;">
                <div style="height: 65px"></div>
                <div style="background-color:gray;width: 900px;height: 558px">
                    <div style="width: 900px;height: 350px">
                        <div class="plate-bottom" style="width: 900px;line-height: 45px;">
                            <div class="thead" style="width: 900px;line-height: 45px;">
                                <span class="thead-one" style="width: 30%;font-size: 30px"><b style="color: white">屏蔽公司</b></span>
                                <span class="thead-two" style="width: 58%"></span>
                                <span class="thead-three" style="width: 10%;font-size: 30px"><b style="color: white">操作</b></span>
                            </div>
                            <div class="position-list">
                                {% for i in page %}
                                    <div class="position" style="height: 135px">
                                        <div class="select fl">
                                            <input type="checkbox">
                                        </div>
                                        <div class="name fl" style="width: 53%;height: 25px">
                                            <p><span><b style="color: #005cbf">{{ i.company_name }}</b> </span></p>
                                        </div>
                                        <div class="edit fr" style="width: 12%;color: crimson">
                                            <a class="open" href="{% url 'NB:cancel_pingbi' i.company_name %}" style="color: crimson">取消屏蔽</a>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                        <div class="plate-bottom" style="width: 900px;height: 30px;background-color: gray">
                            <div class="thead"
                                 style="width: 900px;height: 30px;background-color: gray;line-height: 70px;font-size: 15px">
                                <span style="width: 5%"></span>
                                    <a href="{% url 'NB:user_pbgs' 1 %}"><span style="width: 10%">首页</span></a>
                                {% if page.has_previous %}
                                    <a href="{% url 'NB:user_pbgs' page.previous_page_number %}"><span style="width: 5%">上一页</span></a>
                                {% else %}
                                    <a href="{% url 'NB:user_pbgs' 1 %}"><span style="width: 5%">上一页</span></a>
                                {% endif %}
                                {% if page.has_next %}
                                    <a href="{% url 'NB:user_pbgs' page.next_page_number %}"><span style="width: 5%">下一页</span></a>
                                {% else %}
                                    <a href="{% url 'NB:user_pbgs' paginator.num_pages %}"><span
                                            style="width: 5%">下一页</span></a>
                                {% endif %}
                                <a href="{% url 'NB:user_pbgs' paginator.num_pages %}"><span
                                        style="width: 10%">尾页</span></a>
                            </div>
                        </div>

                    </div>
                </div>

            </div>
        </div>
    </div>
    <div class="row fullscreen d-flex align-items-center justify-content-center">
    </div>
</section>
<footer class="footer-area section-gap" style="height: 250px">
    <div class="container" style="height: 100px">
        <div class="row" style="margin-left: 300px">
            <p>
                <a href="#">关 于 我 们</a>---<a href="#">广 告 合 作 </a>---<a href="#">联 系 我 们 </a>---<a href="#">免 责 声 明 </a>---<a
                    href="#">在 线 投 稿 </a>---<a href="#">投 诉 建 议 </a>
            </p>
        </div>

        <div class="row footer-bottom d-flex justify-content-between" style="margin-left: 305px">

            Copyright &copy;<script>document.write(new Date().getFullYear());</script>
            python1805 NB 0.1 QUAN ZHAN SAN REN PRODUCT. 版权所有
        </div>
    </div>
</footer>
<!-- End footer Area -->

<script src="{% static 'user/mine/jquery-2.2.4.min.js' %}"></script>
<script src="{% static 'user/mine/popper.min.js' %}"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="{% static 'user/mine/bootstrap.min.js' %}"></script>

<script src="{% static 'user/mine/easing.min.js' %}"></script>
<script src="{% static 'user/mine/hoverIntent.js' %}"></script>
<script src="{% static 'user/mine/superfish.min.js' %}"></script>
<script src="{% static 'user/mine/jquery.ajaxchimp.min.js' %}"></script>
<script src="{% static 'user/mine/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'user/mine/owl.carousel.min.js' %}"></script>
<script src="{% static 'user/mine/jquery.sticky.js' %}"></script>
<script src="{% static 'user/mine/jquery.nice-select.min.js' %}"></script>
<script src="{% static 'user/mine/parallax.min.js' %}"></script>
<script src="{% static 'user/mine/mail-script.js' %}"></script>
<script src="{% static 'user/mine/main.js' %}"></script>
</body>
</html>
<script>
    $(function() {
        $('.resume_refresh').click(function () {
            $.getJSON('/resume_refresh/', function (data) {
                if (data['status'] == '200'){
                    alert('简历刷新成功')
                }
                if (data['status'] == '900'){
                    alert('简历刷新失败，请上传简历')
                }
            })

        })

    })
</script>

ZPtest_v01/templates/user/user_skgw.html
<!DOCTYPE html>
{% load static %}
<html lang="zxx" class="no-js">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="">
    <meta name="author" content="codepixer">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta charset="UTF-8">
    <title>欢迎登录博纳人才网</title>

    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'user/mine/linearicons.css' %}">
    <link rel="stylesheet" href="{% static 'user/mine/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'user/mine/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'user/mine/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'user/mine/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'user/mine/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'user/mine/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'user/mine/main.css' %}">
    <link rel="stylesheet" href="{% static 'user/mine/reset.css' %}">
    <link rel="stylesheet" href="{% static 'user/mine/public.css' %}">
    <link rel="stylesheet" href="{% static 'user/mine/recruitmenting.css' %}">
</head>
<body>

<header id="header" id="home">
    <div class="container">
        <div class="row align-items-center justify-content-between d-flex">
            <div id="logo">
                <a style="font-size: 30px">博纳人才网</a>
            </div>
            <nav id="nav-menu-container">
                <ul class="nav-menu">
                    <li class="menu-active"><a href="{% url "NB:go_user_mine" %}">我的主页</a></li>
                    <li class="menu-has-children"><a href="#">简历管理</a>
                        <ul>
                            <li><a href="{% url 'NB:resume_show' %}">简历浏览</a></li>
                            <li><a href="{% url 'NB:find_resume' %}">上传简历</a></li>
                            <li><a class="resume_refresh" href="#">简历刷新</a></li>
                        </ul>
                    </li>
                    <li><a href="{% url 'NB:user_tdjd' 1 %}">投递进度</a></li>
{#                    <li><a href="{% url 'NB:zwss_home' 1 %}">职位搜索</a></li>#}
                    <li><a href="{% url 'NB:user_pbgs' 1 %}">屏蔽公司</a></li>
                    <li><a href="{% url 'NB:user_zwsc' 1 %}">职位收藏</a></li>
                    <li><a href="{% url 'NB:user_skgw' 1 %}">谁看过我</a></li>
                    <li class="menu-has-children"><a href="#">个人中心</a>
                        <ul>
                            <li><a href="{% url 'NB:go_user_reset' %}">找回密码</a></li>
                            <li><a href="{% url 'NB:go_user_vip' %}">会员信息</a></li>
                            <li><a href="{% url 'NB:quit_login' %}">用户注销</a></li>
                        </ul>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
</header>

<section class="banner-area relative" id="home">

    <div class="overlay overlay-bg" style="height: 723px">
        <div style="margin-left: 350px;margin-top: 100px;width:600px;height: 400px">
            <div style="float: left;width: 210px;height: 50px;">
                <p style="font-size: 70px;color: blue;margin-top: 16px"></p>
            </div>
            <div style="float: left;width: 240px;height: 10px">

            </div>
            <div style="width: 800px;height: 400px;">
                <div style="height: 65px"></div>
                <div style="background-color:gray;width: 900px;height: 558px">
                    <div style="width: 900px;height: 350px">
                        <div class="plate-bottom" style="width: 900px;line-height: 45px;">
                            <div class="thead" style="width: 900px;line-height: 45px;">
                                <span class="thead-one" style="width: 30%;font-size: 30px"><b style="color: white">谁看过我</b></span>
                                <span class="thead-two" style="width: 58%"></span>
                                <span class="thead-three" style="width: 10%;font-size: 30px"><b style="color: white">操作</b></span>
                            </div>
                            <div class="position-list">
                                {% for i in page %}
                                <div class="position" style="height: 135px">
                                    <div class="select fl">
                                        <input type="checkbox">
                                    </div>
                                    <div class="name fl" style="width: 53%;height: 25px">
                                        <p><span><b style="color: #005cbf">{{ i.company_name }}</b> </span></p>
                                    </div>
                                    <div class="edit fr" style="width: 12%;color: crimson">
                                        <a class="open" href="{% url 'NB:company_show' i.id %}" style="color: crimson">公司信息</a>
                                    </div>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                        <div class="plate-bottom" style="width: 900px;height: 30px;background-color: gray">
                            <div class="thead"
                                 style="width: 900px;height: 30px;background-color: gray;line-height: 70px;font-size: 15px">
                                <span style="width: 5%"></span>
                                    <a href="{% url 'NB:user_skgw' 1 %}"><span style="width: 10%">首页</span></a>
                                {% if page.has_previous %}
                                    <a href="{% url 'NB:user_skgw' page.previous_page_number %}"><span style="width: 5%">上一页</span></a>
                                {% else %}
                                    <a href="{% url 'NB:user_skgw' 1 %}"><span style="width: 5%">上一页</span></a>
                                {% endif %}
                                {% if page.has_next %}
                                    <a href="{% url 'NB:user_skgw' page.next_page_number %}"><span style="width: 5%">下一页</span></a>
                                {% else %}
                                    <a href="{% url 'NB:user_skgw' paginator.num_pages %}"><span
                                            style="width: 5%">下一页</span></a>
                                {% endif %}
                                <a href="{% url 'NB:user_skgw' paginator.num_pages %}"><span
                                        style="width: 10%">尾页</span></a>
                            </div>
                        </div>

                    </div>
                </div>

            </div>
        </div>
    </div>
    <div class="row fullscreen d-flex align-items-center justify-content-center">
    </div>
</section>
<footer class="footer-area section-gap" style="height: 250px">
    <div class="container" style="height: 100px">
        <div class="row" style="margin-left: 300px">
            <p>
                <a href="#">关 于 我 们</a>---<a href="#">广 告 合 作 </a>---<a href="#">联 系 我 们 </a>---<a href="#">免 责 声 明 </a>---<a
                    href="#">在 线 投 稿 </a>---<a href="#">投 诉 建 议 </a>
            </p>
        </div>

        <div class="row footer-bottom d-flex justify-content-between" style="margin-left: 305px">

            Copyright &copy;<script>document.write(new Date().getFullYear());</script>
            python1805 NB 0.1 QUAN ZHAN SAN REN PRODUCT. 版权所有
        </div>
    </div>
</footer>
<!-- End footer Area -->

<script src="{% static 'user/mine/jquery-2.2.4.min.js' %}"></script>
<script src="{% static 'user/mine/popper.min.js' %}"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="{% static 'user/mine/bootstrap.min.js' %}"></script>

<script src="{% static 'user/mine/easing.min.js' %}"></script>
<script src="{% static 'user/mine/hoverIntent.js' %}"></script>
<script src="{% static 'user/mine/superfish.min.js' %}"></script>
<script src="{% static 'user/mine/jquery.ajaxchimp.min.js' %}"></script>
<script src="{% static 'user/mine/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'user/mine/owl.carousel.min.js' %}"></script>
<script src="{% static 'user/mine/jquery.sticky.js' %}"></script>
<script src="{% static 'user/mine/jquery.nice-select.min.js' %}"></script>
<script src="{% static 'user/mine/parallax.min.js' %}"></script>
<script src="{% static 'user/mine/mail-script.js' %}"></script>
<script src="{% static 'user/mine/main.js' %}"></script>
</body>
</html>
<script>
    $(function() {
        $('.resume_refresh').click(function () {
            $.getJSON('/resume_refresh/', function (data) {
                if (data['status'] == '200'){
                    alert('简历刷新成功')
                }
                if (data['status'] == '900'){
                    alert('简历刷新失败，请上传简历')
                }
            })

        })

    })
</script>

ZPtest_v01/templates/user/user_vip.html
<!DOCTYPE html>
{% load static %}
<html lang="zxx" class="no-js">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="">
    <meta name="author" content="codepixer">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta charset="UTF-8">
    <title>欢迎登录博纳人才网</title>

    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'user/mine/linearicons.css' %}">
    <link rel="stylesheet" href="{% static 'user/mine/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'user/mine/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'user/mine/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'user/mine/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'user/mine/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'user/mine/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'user/mine/main.css' %}">
    <link rel="stylesheet" href="{% static 'user/mine/reset.css' %}">
    <link rel="stylesheet" href="{% static 'user/mine/public.css' %}">
    <link rel="stylesheet" href="{% static 'user/mine/recruitmenting.css' %}">
</head>
<body>

<header id="header" id="home">
    <div class="container">
        <div class="row align-items-center justify-content-between d-flex">
            <div id="logo">
                <a style="font-size: 30px">博纳人才网</a>
            </div>
            <nav id="nav-menu-container">
                <ul class="nav-menu">
                    <li class="menu-active"><a href="{% url "NB:go_user_mine" %}">我的主页</a></li>
                    <li class="menu-has-children"><a href="#">简历管理</a>
                        <ul>
                            <li><a href="{% url 'NB:find_resume' %}">简历浏览</a></li>
                            <li><a href="{% url 'NB:find_resume' %}">上传简历</a></li>
                            <li><a class="resume_refresh" href="#">简历刷新</a></li>
                        </ul>
                    </li>
                    <li><a href="{% url 'NB:user_tdjd' 1 %}">投递进度</a></li>
{#                    <li><a href="{% url 'NB:zwss_home' 1 %}">职位搜索</a></li>#}
                    <li><a href="{% url 'NB:user_pbgs' 1 %}">屏蔽公司</a></li>
                    <li><a href="{% url 'NB:user_zwsc' 1 %}">职位收藏</a></li>
                    <li><a href="{% url 'NB:user_skgw' 1 %}">谁看过我</a></li>
                    <li class="menu-has-children"><a href="#">个人中心</a>
                        <ul>
                            <li><a href="{% url 'NB:go_user_reset' %}">找回密码</a></li>
                            <li><a href="{% url 'NB:go_user_vip' %}">会员信息</a></li>
                            <li><a href="{% url 'NB:quit_login' %}">用户注销</a></li>
                        </ul>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
</header>
<section class="banner-area relative" id="home">

    <div class="overlay overlay-bg" style="height: 723px">
        <div style="margin-left: 15%;margin-top: 7%;width:600px;height: 400px">
            <div style="width: 800px;height: 400px;">
                <div style="height: 15%"></div>
                <div style="background-color:white;width: 900px;height: 558px">
                    <div>
                        <div style="height: 20px"></div>
                        <div style="font-size: 25px;width: 12%;height:10%;"><b style="color: black">会员内容</b></div>

                        <hr>
                        <hr>
                        <table border="1"
                               style="margin-top: 5%;margin-left: 15%;width: 70%;height:300px;text-align: center;vertical-align: center">
                            <tr style="height: 20%">
                                <th>非会员</th>
                                <th>会员</th>
                            </tr>
                            <tr style="height: 40%">
                                <td valign="middle">只能看到一条企业查看纪录</td>
                                <td>可查看3天内的企业查看纪录</td>
                            </tr>
                            <tr style="height: 40%">
                                <td valign="middle">不能查看在求职者的竞争力</td>
                                <td>可以查看在求职者的竞争力</td>
                            </tr>
                        </table>
                        <div style="margin-top: 10%;margin-left: 35%">
                            <button href=""><b style="color: red">点击购买</b>￥69.0</button>
                            <button href="" style="margin-left: 10%"><b style="color: black">取消</b></button>
                        </div>
                    </div>

                </div>

            </div>
        </div>
    </div>
    <div class="row fullscreen d-flex align-items-center justify-content-center">
    </div>
</section>
<footer class="footer-area section-gap" style="height: 250px">
    <div class="container" style="height: 100px">
        <div class="row" style="margin-left: 300px">
            <p>
                <a href="#">关 于 我 们</a>---<a href="#">广 告 合 作 </a>---<a href="#">联 系 我 们 </a>---<a href="#">免 责 声 明 </a>---<a
                    href="#">在 线 投 稿 </a>---<a href="#">投 诉 建 议 </a>
            </p>
        </div>

        <div class="row footer-bottom d-flex justify-content-between" style="margin-left: 305px">

            Copyright &copy;<script>document.write(new Date().getFullYear());</script>
            python1805 NB 0.1 QUAN ZHAN SAN REN PRODUCT. 版权所有
        </div>
    </div>
</footer>
<!-- End footer Area -->

<script src="{% static 'user/mine/jquery-2.2.4.min.js' %}"></script>
<script src="{% static 'user/mine/popper.min.js' %}"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="{% static 'user/mine/bootstrap.min.js' %}"></script>

<script src="{% static 'user/mine/easing.min.js' %}"></script>
<script src="{% static 'user/mine/hoverIntent.js' %}"></script>
<script src="{% static 'user/mine/superfish.min.js' %}"></script>
<script src="{% static 'user/mine/jquery.ajaxchimp.min.js' %}"></script>
<script src="{% static 'user/mine/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'user/mine/owl.carousel.min.js' %}"></script>
<script src="{% static 'user/mine/jquery.sticky.js' %}"></script>
<script src="{% static 'user/mine/jquery.nice-select.min.js' %}"></script>
<script src="{% static 'user/mine/parallax.min.js' %}"></script>
<script src="{% static 'user/mine/mail-script.js' %}"></script>
<script src="{% static 'user/mine/main.js' %}"></script>
</body>
</html>
<script>
    $(function() {
        $('.resume_refresh').click(function () {
            $.getJSON('/resume_refresh/', function (data) {
                if (data['status'] == '200'){
                    alert('简历刷新成功')
                }
                if (data['status'] == '900'){
                    alert('简历刷新失败，请上传简历')
                }
            })

        })

    })
</script>
