ZPtest_v01/ZPtest/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls', namespace='NB'))
]

ZPtest_v01/myapp/urls.py
from django.urls import path

from myapp.views import *

app_name = 'NB'

urlpatterns = [
    path('company_home/', company_home, name='company_home'),
    path('company_register_home/', company_register_home, name='company_register_home'),
    path('company_register/', company_register, name='company_register'),
    path('company_login/', company_login, name='company_login'),
    path('go_company_reset/', go_company_reset, name='go_company_reset'),
    path('go_company_mine/', go_company_mine, name='go_company_mine'),
    path('go_company_vip/', go_company_vip, name='go_company_vip'),
    path('go_company_zhiweisousuo/<pagenum>/', go_company_zhiweisousuo, name='go_company_zhiweisousuo'),
    path('go_company_shoujianxiang/<pagenum>/', go_cpmpany_shoujianxiang, name='go_cpmpany_shoujianxiang'),
    path('go_company_rencaijia/<pagenum>/', go_company_recaija, name='go_company_recaijia'),
    path('company_set/', email_phone_set, name='company_set'),
    path('company_reset/', email_phone_reset, name='company_reset'),
    path('set_phone/', set_phone, name='set_phone'),
    path('set_email/', set_email, name='set_email'),
    path('change_company/',change_company,name='change_company'),
    path('check_resume/<id>/',check_resume,name='check_resume'),
    path('download_resume/',download_resume,name='download_resume'),
    path('jiaru_resume/',jiaru_resume,name='jiaru_resume'),
    path('job_save/', job_release, name='job_save'),
    path('goumai_vip/',goumai_vip,name='goumai_vip'),
    path('xia_xian/<id>/',xia_xian,name='xia_xian'),
    path('re_resume/<id>/',re_resume,name='re_resume'),
    path('upload_job_home/',upload_job_home,name='upload_job_home'),
    path('company_user_name/', company_user_name, name='company_user_name'),
    path('company_name/', company_name, name='company_name'),
    path('search_company_job/<pagenum>/', search_company_job, name='search_company_job'),

    path('user_home/', user_home, name='user_home'),
    path('user_register_home/', user_register_home, name='user_register_home'),
    path('user_register/', user_register, name='user_register'),
    path('user_login/', user_login, name='user_login'),
    path('go_user_reset/', go_user_reset, name='go_user_reset'),
    path('go_user_mine/', go_user_mine, name='go_user_mine'),
    path('zwss_home/<pagenum>/', zwss_home, name='zwss_home'),
    path('user_set/', email_phone_set, name='user_set'),
    path('user_reset/', email_phone_reset, name='user_reset'),
    path('go_user_vip/', go_user_vip, name='go_user_vip'),
    path('user_zwsc/<pagenum>/', go_user_zwsc, name='user_zwsc'),
    path('user_tdjd/<pagenum>/', go_user_tdjd, name='user_tdjd'),
    path('user_pbgs/<pagenum>/', go_user_pbgs, name='user_pbgs'),
    path('user_skgw/<pagenum>/', go_user_skgw, name='user_skgw'),
    path('resume_show/', go_user_jlll, name='resume_show'),
    path('resume_upload/', go_resume_upload, name='resume_upload'),
    path('img/', img, name='img'),
    path('save_xinxi/', save_xinxi, name='save_xinxi'),
    path('change_xinxi/', change_xinxi, name='change_xinxi'),
    path('find_resume/', find_resume, name='find_resume'),
    path('resume_refresh/', resume_refresh, name='resume_refresh'),
    path('cancel_pingbi/<name>/', cancel_pingbi, name='cancel_pingbi'),
    path('zhiweishoucang_toudi/', zhiweishoucang_toudi, name='zhiweishoucang_toudi'),
    path('zhiweishoucang_shanchu/<id>/', zhiweishoucang_shanchu, name='zhiweishoucang_shanchu'),
    path('zhiwei_show/<id>/', zhiwei_show, name='zhiwei_show'),
    path('pingbi_company/', pingbi_company, name='pingbi_company'),
    path('company_show/<id>/', company_show, name='company_show'),
    path('collect_zhiwei/', collect_zhiwei, name='collect_zhiwei'),

    path('quit_login/', quit_login, name='quit_login'),
]

ZPtest_v01/templates/company_rencaijia.html
<!DOCTYPE html>
{% load static %}
<html lang="zxx" class="no-js">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="img/fav.png">
    <meta name="author" content="codepixer">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta charset="UTF-8">
    <title>欢迎登录博纳人才网</title>

    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'company/linearicons.css' %}">
    <link rel="stylesheet" href="{% static 'company/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'company/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'company/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'company/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'company/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'company/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'company/main.css' %}">
    <link rel="stylesheet" href="{% static 'list_yemian/reset.css' %}">
    <link rel="stylesheet" href="{% static 'list_yemian/public.css' %}">
    <link rel="stylesheet" href="{% static 'list_yemian/recruitmenting.css' %}">
</head>
<body>

<header id="header" id="home">
    <div class="container">
        <div class="row align-items-center justify-content-between d-flex">
            <div id="logo">
                <a style="font-size: 30px">博纳人才网</a>
            </div>
            <nav id="nav-menu-container">
                <ul class="nav-menu">
                    <li class="menu-active"><a href="{% url "NB:go_company_mine" %}">我的主页</a></li>
                    <li class="menu-has-children"><a href="">职位管理</a>
                        <ul>
                            <li><a href="{% url 'NB:upload_job_home' %}">职位发布</a></li>
                            <li><a href="{% url 'NB:go_company_zhiweisousuo' 1 %}">查看发布岗位</a></li>
                        </ul>
                    </li>
                    <li><a href="">简历搜索</a></li>
                    <li><a href="{% url 'NB:go_cpmpany_shoujianxiang' 1 %}">收件箱</a></li>
                    <li><a href="{% url 'NB:go_company_recaijia' 1 %}">公司人才夹</a></li>
                    <li class="menu-has-children"><a href="">个人中心</a>
                        <ul>
                            <li><a href="{% url 'NB:change_company' %}">修改公司基本信息</a></li>
                            <li><a href="{% url 'NB:go_company_reset' %}">找回密码</a></li>
                            <li><a href="{% url 'NB:go_company_vip' %}">会员信息</a></li>
                            <li><a href="{% url 'NB:quit_login' %}">用户注销</a></li>
                        </ul>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
</header>

<section class="banner-area relative" id="home">

    <div class="overlay overlay-bg" style="height: 723px">
        <div style="margin-left: 350px;margin-top: 100px;width:600px;height: 400px">
            <div style="float: left;width: 280px;height: 50px;">
                <p style="font-size: 55px;color: blue;margin-top: 12px">我的人才夹</p>
            </div>
            <div style="width: 800px;height: 400px;">
                <div style="height: 52px"></div>
                <div style="background-color:gray;width: 900px;height: 558px">
                    <div style="width: 900px;height: 350px">
                        <div class="plate-bottom" style="width: 700px;line-height: 45px">
                            <div class="thead" style="width: 900px;line-height: 45px">
                                <span class="thead-one">简历id</span>
                                <span class="thead-two">姓名</span>
                                <span class="thead-three">学历</span>
                                <span class="thead-four">城市</span>
                                <span class="thead-five">刷新时间</span>
                            </div>
                        </div>
                        {% for foo in page %}
                        <div class="plate-bottom" style="width: 700px;height: 30px;">
                            <a href="{% url 'NB:re_resume' foo.id %}">
                                <div class="thead" style="width: 900px;background-color: cornflowerblue">
                                    <span class="thead-one">{{ foo.id }}</span>
                                    <span class="thead-two">{{ foo.user_name }}</span>
                                    <span class="thead-three">{{ foo.xueli }}</span>
                                    <span class="thead-four">{{ foo.city }}</span>
                                    <span class="thead-five">{{ foo.resume_time }}</span>
                                </div>
                            </a>
                        </div>
                        {% endfor %}

                        <div class="plate-bottom" style="width: 700px;height: 30px;background-color: gray">
                            <div class="thead"
                                 style="width: 900px;height: 30px;background-color: gray;line-height: 35px">
                                <span style="width: 40%">页码</span>

                                <a href="{% url 'NB:go_company_recaijia' 1 %}"><span style="width: 10%">首页</span></a>
                                {% if page.has_previous %}
                                    <a href="{% url 'NB:go_company_recaijia' page.previous_page_number %}"><span style="width: 10%">上一页</span></a>
                                {% else %}
                                    <a href="{% url 'NB:go_company_recaijia' 1 %}"><span style="width: 10%">上一页</span></a>
                                {% endif %}
                                {% if page.has_next %}
                                <a href="{% url 'NB:go_company_recaijia' page.next_page_number %}"><span style="width: 10%">下一页</span></a>
                                    {% else %}
                                <a href="{% url 'NB:go_company_recaijia' paginator.num_pages %}"><span style="width: 10%">下一页</span></a>
                            {% endif %}
                                <a href="{% url 'NB:go_company_recaijia' paginator.num_pages %}"><span style="width: 10%">尾页</span></a>
                            </div>
                        </div>

                    </div>
                </div>

            </div>
        </div>
    </div>
    <div class="row fullscreen d-flex align-items-center justify-content-center">
    </div>
</section>
<footer class="footer-area section-gap" style="height: 250px">
    <div class="container" style="height: 100px">
        <div class="row" style="margin-left: 300px">
            <p>
                <a href="#">关 于 我 们</a>---<a href="#">广 告 合 作 </a>---<a href="#">联 系 我 们 </a>---<a href="#">免 责 声 明 </a>---<a
                    href="#">在 线 投 稿 </a>---<a href="#">投 诉 建 议 </a>
            </p>
        </div>

        <div class="row footer-bottom d-flex justify-content-between" style="margin-left: 305px">

            Copyright &copy;<script>document.write(new Date().getFullYear());</script>
            python1805 NB 0.1 QUAN ZHAN SAN REN PRODUCT. 版权所有
        </div>
    </div>
</footer>
<!-- End footer Area -->

<script src="{% static 'company/jquery-2.2.4.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="{% static 'company/bootstrap.min.js' %}"></script>

<script src="{% static 'company/easing.min.js' %}"></script>
<script src="{% static 'company/hoverIntent.js' %}"></script>
<script src="{% static 'company/superfish.min.js' %}"></script>
<script src="{% static 'company/jquery.ajaxchimp.min.js' %}"></script>
<script src="{% static 'company/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'company/owl.carousel.min.js' %}"></script>
<script src="{% static 'company/jquery.sticky.js' %}"></script>
<script src="{% static 'company/jquery.nice-select.min.js' %}"></script>
<script src="{% static 'company/parallax.min.js' %}"></script>
<script src="{% static 'company/mail-script.js' %}"></script>
<script src="{% static 'company/main.js' %}"></script>
</body>
</html>




ZPtest_v01/templates/company_shoujianxiang.html
<!DOCTYPE html>
{% load static %}
<html lang="zxx" class="no-js">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="img/fav.png">
    <meta name="author" content="codepixer">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta charset="UTF-8">
    <title>欢迎登录博纳人才网</title>

    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'company/linearicons.css' %}">
    <link rel="stylesheet" href="{% static 'company/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'company/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'company/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'company/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'company/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'company/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'company/main.css' %}">
    <link rel="stylesheet" href="{% static 'list_yemian/reset.css' %}">
    <link rel="stylesheet" href="{% static 'list_yemian/public.css' %}">
    <link rel="stylesheet" href="{% static 'list_yemian/recruitmenting.css' %}">
</head>
<body>

<header id="header" id="home">
    <div class="container">
        <div class="row align-items-center justify-content-between d-flex">
            <div id="logo">
                <a style="font-size: 30px">博纳人才网</a>
            </div>
            <nav id="nav-menu-container">
                <ul class="nav-menu">
                    <li class="menu-active"><a href="{% url "NB:go_company_mine" %}">我的主页</a></li>
                    <li class="menu-has-children"><a href="">职位管理</a>
                        <ul>
                            <li><a href="{% url 'NB:upload_job_home' %}">职位发布</a></li>
                            <li><a href="{% url 'NB:go_company_zhiweisousuo' 1 %}">查看发布岗位</a></li>
                        </ul>
                    </li>
                    <li><a href="">简历搜索</a></li>
                    <li><a href="{% url 'NB:go_cpmpany_shoujianxiang' 1 %}">收件箱</a></li>
                    <li><a href="{% url 'NB:go_company_recaijia' 1 %}">公司人才夹</a></li>
                    <li class="menu-has-children"><a href="">个人中心</a>
                        <ul>
                            <li><a href="{% url 'NB:change_company' %}">修改公司基本信息</a></li>
                            <li><a href="{% url 'NB:go_company_reset' %}">找回密码</a></li>
                            <li><a href="{% url 'NB:go_company_vip' %}">会员信息</a></li>
                            <li><a href="{% url 'NB:quit_login' %}">用户注销</a></li>
                        </ul>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
</header>

<section class="banner-area relative" id="home">

    <div class="overlay overlay-bg" style="height: 723px">
        <div style="margin-left: 350px;margin-top: 100px;width:600px;height: 400px">
            <div style="float: left;width: 210px;height: 50px;">
                <p style="font-size: 70px;color: blue;margin-top: 16px">收件箱</p>
            </div>
            <div style="float: left;width: 240px;height: 10px">
                <img style="width:80px;height: 60px;" src="{% static 'img/e1.jpg' %}">
            </div>
            <div style="width: 800px;height: 400px;">
                <div style="height: 65px"></div>
                <div style="background-color:gray;width: 900px;height: 558px">
                    <div style="width: 900px;height: 350px">
                        <div class="plate-bottom" style="width: 700px;line-height: 45px">
                            <div class="thead" style="width: 900px;line-height: 45px">
                                <span class="thead-one">简历id</span>
                                <span class="thead-two">姓名</span>
                                <span class="thead-three">学历</span>
                                <span class="thead-four">投递岗位</span>
                                <span class="thead-five">刷新时间</span>
                            </div>
                        </div>
                        {% for resume in page %}
                            <div class="plate-bottom" style="width: 700px;height: 30px;">
                                <a href="{% url 'NB:re_resume' resume.id %}">
                                    <div class="thead" style="width: 900px;background-color: cornflowerblue">
                                        <span class="thead-one">{{ resume.id }}</span>
                                        <span class="thead-two">{{ resume.user_name }}</span>
                                        <span class="thead-three">{{ resume.xueli }}</span>
                                        <span class="thead-four">{{ resume.job_title }}</span>
                                        <span class="thead-five">{{ resume.resume_time }}</span>
                                    </div>
                                </a>
                            </div>
                        {% endfor %}
                        <div class="plate-bottom" style="width: 700px;height: 20px">
                            <div class="thead" style="width: 900px;line-height: 45px;height: 20px">
                            </div>
                        </div>
                        <div class="plate-bottom" style="width: 700px;height: 30px;background-color: gray">
                            <div class="thead"
                                 style="width: 900px;height: 30px;background-color: gray;line-height: 45px">
                                <span style="width: 40%">页码</span>

                                <a href="{% url 'NB:go_cpmpany_shoujianxiang' 1 %}"><span style="width: 10%">首页</span></a>
                                {% if page.has_previous %}
                                    <a href="{% url 'NB:go_cpmpany_shoujianxiang' page.previous_page_number %}"><span style="width: 10%">上一页</span></a>
                                {% else %}
                                    <a href="{% url 'NB:go_cpmpany_shoujianxiang' 1 %}"><span style="width: 10%">上一页</span></a>
                                {% endif %}
                                {% if page.has_next %}
                                <a href="{% url 'NB:go_cpmpany_shoujianxiang' page.next_page_number %}"><span style="width: 10%">下一页</span></a>
                                    {% else %}
                                <a href="{% url 'NB:go_cpmpany_shoujianxiang' paginator.num_pages %}"><span style="width: 10%">下一页</span></a>
                            {% endif %}
                                <a href="{% url 'NB:go_cpmpany_shoujianxiang' paginator.num_pages %}"><span style="width: 10%">尾页</span></a>
                            </div>
                        </div>

                    </div>
                </div>

            </div>
        </div>
    </div>
    <div class="row fullscreen d-flex align-items-center justify-content-center">
    </div>
</section>
<footer class="footer-area section-gap" style="height: 250px">
    <div class="container" style="height: 100px">
        <div class="row" style="margin-left: 300px">
            <p>
                <a href="#">关 于 我 们</a>---<a href="#">广 告 合 作 </a>---<a href="#">联 系 我 们 </a>---<a href="#">免 责 声 明 </a>---<a
                    href="#">在 线 投 稿 </a>---<a href="#">投 诉 建 议 </a>
            </p>
        </div>

        <div class="row footer-bottom d-flex justify-content-between" style="margin-left: 305px">

            Copyright &copy;<script>document.write(new Date().getFullYear());</script>
            python1805 NB 0.1 QUAN ZHAN SAN REN PRODUCT. 版权所有
        </div>
    </div>
</footer>
<!-- End footer Area -->

<script src="{% static 'company/jquery-2.2.4.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="{% static 'company/bootstrap.min.js' %}"></script>

<script src="{% static 'company/easing.min.js' %}"></script>
<script src="{% static 'company/hoverIntent.js' %}"></script>
<script src="{% static 'company/superfish.min.js' %}"></script>
<script src="{% static 'company/jquery.ajaxchimp.min.js' %}"></script>
<script src="{% static 'company/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'company/owl.carousel.min.js' %}"></script>
<script src="{% static 'company/jquery.sticky.js' %}"></script>
<script src="{% static 'company/jquery.nice-select.min.js' %}"></script>
<script src="{% static 'company/parallax.min.js' %}"></script>
<script src="{% static 'company/mail-script.js' %}"></script>
<script src="{% static 'company/main.js' %}"></script>
</body>
</html>




ZPtest_v01/templates/company_zhiweilist.html
<!DOCTYPE html>
{% load static %}
<html lang="zxx" class="no-js">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="img/fav.png">
    <meta name="author" content="codepixer">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta charset="UTF-8">
    <title>欢迎登录博纳人才网</title>

    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'company/linearicons.css' %}">
    <link rel="stylesheet" href="{% static 'company/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'company/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'company/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'company/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'company/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'company/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'company/main.css' %}">
    <link rel="stylesheet" href="{% static 'list_yemian/reset.css' %}">
    <link rel="stylesheet" href="{% static 'list_yemian/public.css' %}">
    <link rel="stylesheet" href="{% static 'list_yemian/recruitmenting.css' %}">
</head>
<body>

<header id="header" id="home">
    <div class="container">
        <div class="row align-items-center justify-content-between d-flex">
            <div id="logo">
                <a style="font-size: 30px">博纳人才网</a>
            </div>
            <nav id="nav-menu-container">
                <ul class="nav-menu">
                    <li class="menu-active"><a href="{% url "NB:go_company_mine" %}">我的主页</a></li>
                    <li class="menu-has-children"><a href="">职位管理</a>
                        <ul>
                            <li><a href="{% url 'NB:upload_job_home' %}">职位发布</a></li>
                            <li><a href="{% url 'NB:go_company_zhiweisousuo' 1 %}">查看发布岗位</a></li>
                        </ul>
                    </li>
                    <li><a href="">简历搜索</a></li>
                    <li><a href="{% url 'NB:go_cpmpany_shoujianxiang' 1 %}">收件箱</a></li>
                    <li><a href="{% url 'NB:go_company_recaijia' 1 %}">公司人才夹</a></li>
                    <li class="menu-has-children"><a href="">个人中心</a>
                        <ul>
                            <li><a href="{% url 'NB:change_company' %}">修改公司基本信息</a></li>
                            <li><a href="{% url 'NB:go_company_reset' %}">找回密码</a></li>
                            <li><a href="{% url 'NB:go_company_vip' %}">会员信息</a></li>
                            <li><a href="{% url 'NB:quit_login' %}">用户注销</a></li>
                        </ul>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
</header>

<section class="banner-area relative" id="home">

    <div class="overlay overlay-bg" style="height: 723px">
        <div style="margin-left: 350px;margin-top: 100px;width:600px;height: 400px">
            <div style="float: left;width: 210px;height: 50px;">
                <p style="font-size: 70px;color: blue;margin-top: 16px"></p>
            </div>
            <div style="float: left;width: 240px;height: 10px">

            </div>
            <div style="width: 800px;height: 400px;">
                <div style="height: 65px"></div>
                <div style="background-color:gray;width: 900px;height: 558px">
                    <div style="width: 900px;height: 350px">
                        <div class="plate-bottom" style="width: 900px;line-height: 45px;">
                            <div class="thead" style="width: 900px;line-height: 45px;">
                                <span class="thead-one" style="width: 30%;font-size: 30px"><b
                                        style="color: white">职位信息</b></span>
                                <span class="thead-two" style="width: 58%"></span>
                                <span class="thead-three" style="width: 10%;font-size: 30px"><b
                                        style="color: white">操作</b></span>
                            </div>
                            <div class="position-list">
                                {% for job in page %}

                                    <div class="position" style="height: 135px">
                                        <div class="select fl">
                                            <input type="checkbox" disabled>
                                        </div>
                                        <div class="name fl" style="width: 53%;height: 25px">
                                            <p><span><b style="color: #005cbf">{{ job.job_name }}</b> </span></p>
                                            <ul style="color: black">
                                                <li>{{ job.job_city }}</li>
                                                <li>|</li>
                                                <li>{{ job.work_year }}</li>
                                                <li>|</li>
                                                <li>{{ job.xueli }}</li>
                                                <li>|</li>
                                                <li>{{ job.money }}</li>
                                            </ul>
                                        </div>
                                        <div class="edit fr" style="width: 12%;color: crimson">
                                            <a class="open" href="{% url 'NB:xia_xian' 1 %}" style="color: crimson">下线</a>&nbsp;&nbsp;
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                        <div class="plate-bottom" style="width: 900px;height: 30px;background-color: gray">
                            <div class="thead"
                                 style="width: 900px;height: 30px;background-color: gray;line-height: 70px;font-size: 15px">
                                <span style="width: 5%"></span>
                                <a href="{% url 'NB:go_company_zhiweisousuo' 1 %}"><span style="width: 10%">首页</span></a>
                                {% if page.has_previous %}
                                    <a href="{% url 'NB:go_company_zhiweisousuo' page.previous_page_number %}"><span
                                            style="width: 5%">上一页</span></a>
                                {% else %}
                                    <a href="{% url 'NB:go_company_zhiweisousuo' 1 %}"><span style="width: 5%">上一页</span></a>
                                {% endif %}
                                {% if page.has_next %}
                                    <a href="{% url 'NB:go_company_zhiweisousuo' page.next_page_number %}"><span
                                            style="width: 5%">下一页</span></a>
                                {% else %}
                                    <a href="{% url 'NB:go_company_zhiweisousuo' paginator.num_pages %}"><span
                                            style="width: 5%">下一页</span></a>
                                {% endif %}
                                <a href="{% url 'NB:go_company_zhiweisousuo' paginator.num_pages %}"><span
                                        style="width: 10%">尾页</span></a>
                            </div>
                        </div>

                    </div>
                </div>

            </div>
        </div>
    </div>
    <div class="row fullscreen d-flex align-items-center justify-content-center">
    </div>
</section>
<footer class="footer-area section-gap" style="height: 250px">
    <div class="container" style="height: 100px">
        <div class="row" style="margin-left: 300px">
            <p>
                <a href="#">关 于 我 们</a>---<a href="#">广 告 合 作 </a>---<a href="#">联 系 我 们 </a>---<a href="#">免 责 声 明 </a>---<a
                    href="#">在 线 投 稿 </a>---<a href="#">投 诉 建 议 </a>
            </p>
        </div>

        <div class="row footer-bottom d-flex justify-content-between" style="margin-left: 305px">

            Copyright &copy;<script>document.write(new Date().getFullYear());</script>
            python1805 NB 0.1 QUAN ZHAN SAN REN PRODUCT. 版权所有
        </div>
    </div>
</footer>
<!-- End footer Area -->

<script src="{% static 'company/jquery-2.2.4.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="{% static 'company/bootstrap.min.js' %}"></script>

<script src="{% static 'company/easing.min.js' %}"></script>
<script src="{% static 'company/hoverIntent.js' %}"></script>
<script src="{% static 'company/superfish.min.js' %}"></script>
<script src="{% static 'company/jquery.ajaxchimp.min.js' %}"></script>
<script src="{% static 'company/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'company/owl.carousel.min.js' %}"></script>
<script src="{% static 'company/jquery.sticky.js' %}"></script>
<script src="{% static 'company/jquery.nice-select.min.js' %}"></script>
<script src="{% static 'company/parallax.min.js' %}"></script>
<script src="{% static 'company/mail-script.js' %}"></script>
<script src="{% static 'company/main.js' %}"></script>
</body>
</html>


